# Generated by Django 4.2.3 on 2023-07-27 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="profile_pictures"),
                ),
                ("links", models.ManyToManyField(to="linktastic.link")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLinkDisplayPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("12px", "Small"),
                            ("16px", "Medium"),
                            ("20px", "Large"),
                        ],
                        default="16px",
                        max_length=10,
                    ),
                ),
                (
                    "font_color",
                    models.CharField(
                        choices=[("black", "Black"), ("blue", "Blue"), ("red", "Red")],
                        default="black",
                        max_length=10,
                    ),
                ),
                ("font", models.CharField(default="default_font", max_length=100)),
                (
                    "button_shape",
                    models.CharField(
                        choices=[("SQUARE", "Square"), ("ROUNDED", "Rounded")],
                        default="SQUARE",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("STAR", "Star"),
                            ("HEART", "Heart"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User link display preferences",
            },
        ),
    ]
